export function json() {
          return {"Driver Requirements": ["Helmet - SA2010",
                                      "Correct Clothing",
                                      "Tire pressure gauge"],
              "Vehicle - General": ["Loose items Removed",
                                  "Fire Extinguisher with metal bracket"],
              "Vehicle - Engine/Drivetrain": ["No leaks",
                                            "Heat Shield",
                                            "Overflow tanks",
                                            "Correct Fuel line and clamps"],
              "Vehicle - Electrical": ["Battery Tie Down",
                                     "Brake Lights",
                                     "Hazard Lights",
                                     "Key shut off"],
              "Vehicle - Suspension": ["Arms and bushings",
                                     "No play in bearings",
                                     "Smooth Steering",
                                     "Lug Nuts"],
              "Vehicle - Body": ["Tow Hooks",
                               "Hood latch",
                               "Windshield - no cracks"],
              "Vehicle - Roll Cage (if applicable)": ["Roll bar if convertible",
                                                      "Roll cage design",
                                                      "Door Bars",
                                                      "Welds",
                                                      "Padding"],
              "Vehicle - Harnesses and Seats": ["Harness Mounting",
                                                "Harness expiration date",
                                                "Seat and harness configuration"]
            }
          }
